# -*- coding: utf-8 -*-
"""index.html 의 const LAY 블록(시나리오별 헥스 배치도)을 만든다.

입력
  tools/dh_cache/<번호>.json   datahaven(Sebaestschjin) 의 Tabletop Simulator 배치 좌표
  tools/ghs_cache/<번호>.json  Gloomhaven Secretariat 데이터 (타일 면 L1a/L1b 판별, 수량 교차 검증)

좌표
  TTS 월드 좌표(x, z)의 헥스 중심 간격은 긴축 1.3125, 짧은축 0.7577718.
  scenario.gridType 이 1이면 (x=긴축, z=짧은축), 2면 뒤바뀐다. 두 축 인덱스 합은 항상 짝수.
  시나리오마다 원점이 다르므로 첫 몬스터(없으면 첫 시작 헥스)를 원점으로 삼는다.

바닥 복원
  타일 한 면의 전체 헥스 목록은 어느 데이터에도 없다. 같은 타일 면을 쓴 모든 시나리오의
  점유 헥스를 평행이동으로 정렬해 합집합을 만들고, 행 단위로 사이를 메워 바닥으로 쓴다.
  따라서 바닥 모양은 추정치다. 몬스터·장애물·문의 헥스 좌표는 원본 그대로다.

사용법
  python tools/fetch_layouts.py             # 원본 내려받기
  python tools/build_map_layout.py --check   # 검증만
  python tools/build_map_layout.py --dump L1a G1b
  python tools/build_map_layout.py           # index.html 갱신
"""
import json, glob, os, collections, math, io, re, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _emit as E

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DH = os.path.join(ROOT, 'tools', 'dh_cache')
GHS = os.path.join(ROOT, 'tools', 'ghs_cache')
HTML = os.path.join(ROOT, 'index.html')

LONG, SHORT = 1.3125, 0.7577718
MARK = '// ---------- hex layout data (generated by tools/build_map_layout.py) ----------\n'
ENDMARK = '// ---------- /hex layout data ----------'


# ---------------------------------------------------------------- 입력

def load():
    D = {}
    for f in glob.glob(os.path.join(DH, '*.json')):
        D[int(os.path.basename(f)[:-5])] = json.load(open(f, encoding='utf-8'))
    G = {}
    for f in glob.glob(os.path.join(GHS, '*.json')):
        d = json.load(open(f, encoding='utf-8'))
        G[int(d['index'])] = d
    return D, G


def room_items(room):
    """(종류, 이름, position, 부가정보)"""
    out = []
    st = room.get('startTiles')
    for g in ([st] if isinstance(st, dict) else (st or [])):
        if isinstance(g, dict):
            for t in g.get('tiles', []):
                if isinstance(t.get('position'), dict):
                    out.append(('start', g.get('name'), t['position'], None))
    for m in room.get('monsters', []):
        for t in m.get('tiles', []):
            if isinstance(t.get('position'), dict):
                out.append(('monster', m.get('name'), t['position'], t.get('numCharacters') or {}))
    for ov in room.get('overlayTiles', []):
        for ty in ov.get('type', []):
            for t in ty.get('tiles', []):
                if isinstance(t.get('position'), dict):
                    out.append(('overlay', ty.get('name'), t['position'], t.get('rotation')))
    return out


def tile_of(room):
    t = (room.get('mapTiles') or [None])[0]
    return t if t and isinstance(t.get('position'), dict) else None


def axes(gt):
    return (LONG, SHORT) if gt == 1 else (SHORT, LONG)


def origin_of(d):
    for room in d.get('rooms', []):
        for kind, name, p, _ in room_items(room):
            if kind == 'monster':
                return p['x'], p['z']
    for room in d.get('rooms', []):
        for kind, name, p, _ in room_items(room):
            return p['x'], p['z']
    return 0.0, 0.0


def world_hex(p, ox, oz, sx, sz):
    c, r = (p['x'] - ox) / sx, (p['z'] - oz) / sz
    return round(c), round(r), max(abs(c - round(c)), abs(r - round(r)))


# ------------------------------------------------- 타일 국소 좌표

def tile_frames(room, gt):
    """방 안의 지도 타일마다 (키, to_local, to_world, tile) 를 만든다.
    방 하나에 타일이 여러 장인 경우가 있으므로(287/1, 33/2, 6/3, 3/4, 1/5) 요소는 가장 가까운 타일에 붙인다."""
    out = []
    for t in (room.get('mapTiles') or []):
        if not isinstance(t.get('position'), dict):
            continue
        th = math.radians(t['rotation']['y'])
        flip = abs(((t['rotation']['z'] + 180) % 360) - 180) > 90
        k = round(t['rotation']['y'] / 30) % 2
        base = axes(gt)
        lsx, lsz = base if k == 0 else base[::-1]
        tx, tz = t['position']['x'], t['position']['z']

        def mk(th=th, flip=flip, lsx=lsx, lsz=lsz, tx=tx, tz=tz):
            def to_local(p):
                dx, dz = p['x'] - tx, p['z'] - tz
                lx = dx * math.cos(th) - dz * math.sin(th)
                lz = dx * math.sin(th) + dz * math.cos(th)
                if flip:
                    lx = -lx
                c, r = lx / lsx, lz / lsz
                return round(c), round(r), max(abs(c - round(c)), abs(r - round(r)))

            def to_world(c, r):
                lx, lz = c * lsx, r * lsz
                if flip:
                    lx = -lx
                x = lx * math.cos(-th) - lz * math.sin(-th)
                z = lx * math.sin(-th) + lz * math.cos(-th)
                return {'x': x + tx, 'z': z + tz}
            return to_local, to_world
        to_local, to_world = mk()
        # 같은 물리적 타일 면끼리 묶는 키 (a/b 이름은 GHS 쪽에서 따로 받아 표시용으로만 쓴다)
        key = (t.get('tile'), bool(flip), k)
        out.append((key, to_local, to_world, t))
    return out


def nearest(frames, p):
    best = None
    for fr in frames:
        t = fr[3]['position']
        d = (t['x'] - p['x']) ** 2 + (t['z'] - p['z']) ** 2
        if best is None or d < best[0]:
            best = (d, fr)
    return best[1] if best else None


# ------------------------------------------------- 바닥 모양 복원

def uses_by_face(D, G):
    """타일 면 키 -> [(시나리오, 방, 타일 index, 국소 점유 헥스 set)]"""
    out = collections.defaultdict(list)
    for i, d in sorted(D.items()):
        gt = d.get('gridType', 1)
        for ri, room in enumerate(d.get('rooms', []), 1):
            frames = tile_frames(room, gt)
            if not frames:
                continue
            acc = collections.defaultdict(set)
            for kind, name, p, extra in room_items(room):
                if kind == 'start' or (name and 'Corridor' in str(name)):
                    continue
                fr = nearest(frames, p)
                c, r, res = fr[1](p)
                if res <= 0.2:
                    acc[id(fr[3])].add((c, r))
            for ti, fr in enumerate(frames):
                out[fr[0]].append((i, ri, ti, acc.get(id(fr[3]), set())))
    return out


def align(ref, other, span=7):
    """other 를 ref 에 가장 잘 겹치도록 평행이동."""
    if not other:
        return (0, 0, 0)
    best = (-1, 0, 0)
    for dc in range(-span, span + 1):
        for dr in range(-2 * span, 2 * span + 1):
            n = sum(1 for (c, r) in other if (c + dc, r + dr) in ref)
            if n > best[0] or (n == best[0] and abs(dc) + abs(dr) < abs(best[1]) + abs(best[2])):
                best = (n, dc, dr)
    return best


def rowfill(hexes):
    byrow = collections.defaultdict(list)
    for c, r in hexes:
        byrow[r].append(c)
    out = set()
    for r, cols in byrow.items():
        lo, hi = min(cols), max(cols)
        for c in range(lo, hi + 1, 2):
            out.add((c, r))
    return out


def floors(D, G):
    """(시나리오, 방, 타일index) -> 국소 바닥 헥스 set,  면키 -> 복원 모양"""
    faces = uses_by_face(D, G)
    result, shapes = {}, {}
    for key, uses in faces.items():
        base = max(uses, key=lambda u: len(u[3]))
        acc = set(base[3])
        shifts = {}
        for (i, ri, ti, hexes) in uses:
            if (i, ri, ti) == (base[0], base[1], base[2]):
                shifts[(i, ri, ti)] = (0, 0)
                continue
            n, dc, dr = align(acc, hexes)
            shifts[(i, ri, ti)] = (dc, dr)
            acc |= {(c + dc, r + dr) for (c, r) in hexes}
        shape = rowfill(acc)
        shapes[key] = shape
        for (i, ri, ti, hexes) in uses:
            dc, dr = shifts[(i, ri, ti)]
            result[(i, ri, ti)] = {(c - dc, r - dr) for (c, r) in shape}
    return result, shapes, faces


# ------------------------------------------------- 분류표

# 오버레이 종류 -> (분류, 한국어 이름)
OVL = {
    'Coin 1': ('coin', '돈'),
    'Treasure Chest Horizontal': ('treasure', '보물 상자'),
    'Treasure Chest Vertical': ('treasure', '보물 상자'),
    'Water 1': ('difficult', '물'),
    'Rubble': ('difficult', '잔해'),
    'Stalagmites': ('difficult', '석순'),
    'Thorns': ('hazard', '가시덤불'),
    'Poison Gas': ('hazard', '독가스'),
    'Hot Coals 1': ('hazard', '뜨거운 숯'),
    'Spike Trap': ('trap', '가시 함정'),
    'Bear Trap': ('trap', '곰덫'),
    'Pressure Plate': ('special', '압력판'),
    'Stairs Horizontal': ('special', '계단'),
    'Stairs Vertical': ('special', '계단'),
    'Dark Pit': ('special', '어둠의 구덩이'),
    'Altar Horizontal': ('special', '제단'),
    'Altar Vertical': ('special', '제단'),
    'Crystal': ('special', '수정'),
    'Fountain': ('special', '분수'),
    'Boulder': ('obstacle', '바위'),
    'Boulder 2': ('obstacle', '바위'),
    'Boulder 3': ('obstacle', '바위'),
    'Stone Pillar': ('obstacle', '돌기둥'),
    'Rock Column': ('obstacle', '암석 기둥'),
    'Wall Section': ('obstacle', '벽'),
    'Bush': ('obstacle', '덤불'),
    'Log': ('obstacle', '통나무'),
    'Tree': ('obstacle', '나무'),
    'Stump': ('obstacle', '그루터기'),
    'Barrel': ('obstacle', '통'),
    'Bookcase': ('obstacle', '책장'),
    'Cabinet': ('obstacle', '수납장'),
    'Crate B': ('obstacle', '상자'),
    'Shelf': ('obstacle', '선반'),
    'Table': ('obstacle', '탁자'),
    'Totem': ('obstacle', '토템'),
    'Sarcophagus A': ('obstacle', '석관'),
    'Nest': ('obstacle', '둥지'),
}
DOOR = {
    'Stone Door Horizontal': ('door', '돌문'),
    'Stone Door Vertical': ('door', '돌문'),
    'Wooden Door Horizontal': ('door', '나무문'),
    'Wooden Door Vertical': ('door', '나무문'),
    'Light Fog': ('fog', '옅은 안개'),
    'Dark Fog': ('fog', '짙은 안개'),
}


def classify(name):
    if name in OVL:
        return OVL[name]
    if name in DOOR:
        return DOOR[name]
    if 'Corridor' in str(name):
        return ('corridor', '통로')
    return ('other', str(name))


# ------------------------------------------------- 형태 보정

NB = ((1, 1), (1, -1), (-1, 1), (-1, -1), (0, 2), (0, -2))


def bbox_fill(hexes):
    """복원된 모양의 외접 사각형(헥스 격자 기준)을 채운다. 실제 타일은 대체로 꽉 찬 블록이라
    관측되지 않은 빈 칸까지 메워야 방끼리 맞닿는다. 모서리는 과하게 튀어나올 수 있다."""
    cs = [c for c, r in hexes]; rs = [r for c, r in hexes]
    par = (cs[0] + rs[0]) % 2
    return {(c, r) for c in range(min(cs), max(cs) + 1)
            for r in range(min(rs), max(rs) + 1) if (c + r) % 2 == par}


def close_shape(hexes, rounds=2):
    """이웃이 4칸 이상 차 있으면 메운다 (바닥의 구멍 제거)."""
    cur = set(hexes)
    for _ in range(rounds):
        add = set()
        cs = [c for c, r in cur]; rs = [r for c, r in cur]
        for c in range(min(cs) - 1, max(cs) + 2):
            for r in range(min(rs) - 2, max(rs) + 3):
                if (c, r) in cur or (c + r) % 2 != (min(cs) + min(rs)) % 2:
                    continue
                if sum(1 for dc, dr in NB if (c + dc, r + dr) in cur) >= 4:
                    add.add((c, r))
        if not add:
            break
        cur |= add
    return cur


# ------------------------------------------------- 검증 / 출력

def main():
    D, G = load()
    fl, shapes, faces = floors(D, G)
    mode = 'bbox' if '--bbox' in sys.argv else 'close'
    for k in shapes:
        shapes[k] = bbox_fill(shapes[k]) if mode == 'bbox' else close_shape(rowfill(shapes[k]))
    # 보정된 모양을 각 사용처에 다시 반영
    for key, uses in faces.items():
        base = max(uses, key=lambda u: len(u[3]))
        shape = shapes[key]
        for (i, ri, ti, hexes) in uses:
            n, dc, dr = align(shape, hexes) if hexes else (0, 0, 0)
            fl[(i, ri, ti)] = {(c - dc, r - dr) for (c, r) in shape}

    if '--dump' in sys.argv:
        want = [w.lower() for w in sys.argv[sys.argv.index('--dump') + 1:]]
        for key in sorted(shapes, key=lambda k: -len(shapes[k])):
            if want and key[0].lower() not in want:
                continue
            s_ = shapes[key]
            cmin = min(c for c, r in s_); cmax = max(c for c, r in s_)
            rmin = min(r for c, r in s_); rmax = max(r for c, r in s_)
            print('== %s%s k%d  사용 %d회  헥스 %d개  가로 %d 세로 %d' %
                  (key[0], 'B' if key[1] else 'A', key[2], len(faces[key]), len(s_),
                   cmax - cmin + 1, (rmax - rmin) // 2 + 1))
            for r in range(rmin, rmax + 1):
                print('   ' + ''.join('#' if (c, r) in s_ else ' ' for c in range(cmin, cmax + 1)))
            print()
        return

    sizes = sorted(len(v) for v in shapes.values())
    print('타일 면 %d개 · 방·타일 %d개 · 바닥 중앙 %d헥스 최대 %d헥스'
          % (len(shapes), len(fl), sizes[len(sizes) // 2], sizes[-1]))

    ok, badn, _ = E.cross_check_totals(D, G, room_items)
    print('몬스터 스탠디 총수 GHS 대조: 일치 %d, 차이 %d' % (ok, badn))

    # ---------------- 생성 ----------------
    kor = korean_names()
    names = sorted({norm(n) for i, d in D.items() for room in d.get('rooms', [])
                    for k, n, p, e in room_items(room) if k == 'monster'})
    nidx = {n: i for i, n in enumerate(names)}
    LMON = [kor.get(n, n) for n in names]

    ovkinds = {}
    def ov_index(name):
        cat, ko = classify(name)
        key = (cat, ko)
        if key not in ovkinds:
            ovkinds[key] = len(ovkinds)
        return ovkinds[key]

    LAY = {}
    warn = []
    for i, d in sorted(D.items()):
        gt = d.get('gridType', 1); ox, oz = origin_of(d); sx, sz = axes(gt)
        boss = boss_names(G.get(i, {}))

        def W(p):
            c, r, res = world_hex(p, ox, oz, sx, sz)
            return (r, -c) if gt == 2 else (c, r)     # 방향 통일(90도 회전)

        # 바닥 (겹치는 1.5%%는 그대로 둔다. 같은 색으로 두 번 그려질 뿐이다)
        floors_by_room = collections.defaultdict(set)
        for ri, room in enumerate(d.get('rooms', []), 1):
            for ti, fr in enumerate(tile_frames(room, gt)):
                for (c, r) in fl.get((i, ri, ti), set()):
                    floors_by_room[ri].add(W(fr[2](c, r)))

        rooms = []
        for ri, room in enumerate(d.get('rooms', []), 1):
            frames = tile_frames(room, gt)
            if not frames and not floors_by_room.get(ri):
                continue
            mons, starts, ovs = [], [], []
            for kind, name, p, extra in room_items(room):
                c, r = W(p)
                if kind == 'monster':
                    t = []
                    for pl in ('2', '3', '4'):
                        v = (extra or {}).get(pl)
                        t.append(3 if (v and norm(name) in boss) else (2 if v == 2 else (1 if v == 1 else 0)))
                    if any(t):
                        mons.append([nidx[norm(name)], c, r] + t)
                elif kind == 'start':
                    starts.append([c, r])
                else:
                    ovs.append([ov_index(name), c, r])
            ref = ghref(G.get(i, {}), ri) or ','.join(sorted({str(f[3].get('tile')) for f in frames}))
            ent = {'n': ri, 't': ref, 'f': E.rle(floors_by_room.get(ri, set()))}
            if mons: ent['m'] = mons
            if starts: ent['s'] = starts
            if ovs: ent['v'] = ovs
            rooms.append(ent)

        doors = []
        for dt in d.get('doorTiles', []):
            for t in dt.get('tiles', []):
                if not isinstance(t.get('position'), dict):
                    continue
                c, r = W(t['position'])
                doors.append([ov_index(dt.get('name')), c, r] + sorted(t.get('rooms', []) or []))

        allc = [c for rm in rooms for (rr, c0, n) in rm['f'] for c in (c0, c0 + 2 * (n - 1))]
        allr = [rr for rm in rooms for (rr, c0, n) in rm['f']]
        if not allc:
            continue
        mc, mr = min(allc), min(allr)
        for rm in rooms:
            rm['f'] = [[rr - mr, c0 - mc, n] for (rr, c0, n) in rm['f']]
        # 좌표 이동 (몬스터/시작/오버레이/문)
        def shift(e, ci, ri_):
            e[ci] -= mc; e[ri_] -= mr
        for rm in rooms:
            for e in rm.get('m', []): shift(e, 1, 2)
            for e in rm.get('s', []): shift(e, 0, 1)
            for e in rm.get('v', []): shift(e, 1, 2)
        for e in doors: shift(e, 1, 2)

        ent = {'r': rooms}
        if doors: ent['d'] = doors
        LAY[str(i)] = ent

    OVN = [[k[0], k[1]] for k in sorted(ovkinds, key=ovkinds.get)]
    blob = ('const LMON=%s;\nconst OVN=%s;\nconst LAY=%s;\n' % (
        json.dumps(LMON, ensure_ascii=False, separators=(',', ':')),
        json.dumps(OVN, ensure_ascii=False, separators=(',', ':')),
        json.dumps(LAY, ensure_ascii=False, separators=(',', ':'))))
    html = open(HTML, encoding='utf-8').read()
    st = html.find(MARK)
    if st == -1:
        sys.exit('index.html 에 생성 블록 표시가 없습니다.')
    en = html.find(ENDMARK, st)
    open(HTML, 'w', encoding='utf-8', newline='').write(html[:st + len(MARK)] + blob + html[en:])
    print('LAY %d개 시나리오, 몬스터 %d종, 오버레이 %d종, blob %.1fKB'
          % (len(LAY), len(LMON), len(OVN), len(blob) / 1024))


def norm(n):
    return re.sub(r'[^a-z0-9]+', '-', str(n).lower()).strip('-')


def korean_names():
    """GHS 슬러그 -> 한국어 이름 (index.html 의 MON 배열 재사용)"""
    html = open(HTML, encoding='utf-8').read()
    mon = json.loads(re.search(r'const MON=(\[.*?\]);\n', html, re.S).group(1))
    slugs = sorted({s for f in glob.glob(os.path.join(GHS, '*.json'))
                    for s in json.load(open(f, encoding='utf-8')).get('monsters', [])})
    out = {}
    for name, slug in zip(mon, slugs):
        out[slug.split(':')[0]] = re.sub(r'\s*\(레벨.*\)$', '', name)
    return out


def boss_names(gd):
    out = set()
    for r in gd.get('rooms', []):
        for e in r.get('monster', []):
            if e.get('type') == 'boss':
                out.add(e['name'].split(':')[0])
    return out


def ghref(gd, ri):
    for r in gd.get('rooms', []):
        if r.get('roomNumber') == ri:
            return r.get('ref')
    return None


if __name__ == '__main__':
    main()
