# -*- coding: utf-8 -*-
"""index.html 안의 const MAP / const MON 블록을 Gloomhaven Secretariat 데이터로 다시 만든다.

사용법:
    python tools/fetch_ghs.py        # GHS 시나리오 JSON 95개를 tools/ghs_cache/ 에 내려받음
    python tools/build_battle_data.py  # index.html 갱신

한글 몬스터 이름은 index.html 의 S[id].mons 순서가 GHS scenario.monsters 순서와
같다는 점을 이용해 역으로 만든다. 전 시나리오에서 충돌이 없을 때만 통과한다.
"""
import json, glob, os, re, sys, collections

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML = os.path.join(ROOT, 'index.html')
CACHE = os.path.join(ROOT, 'tools', 'ghs_cache')


def load_html():
    return open(HTML, encoding='utf-8').read()


def parse_const(html, name):
    m = re.search(r'const %s=(\{.*?\});\n' % name, html, re.S)
    return json.loads(m.group(1)), m


def load_ghs():
    D = {}
    for f in sorted(glob.glob(os.path.join(CACHE, '*.json'))):
        d = json.load(open(f, encoding='utf-8'))
        D[int(d['index'])] = d
    if sorted(D) != list(range(1, 96)):
        sys.exit('GHS 캐시가 1~95를 다 담고 있지 않습니다. tools/fetch_ghs.py 를 먼저 실행하세요.')
    return D


def build_monster_names(D, S):
    """slug -> 한글 이름. 충돌이 하나라도 있으면 중단."""
    m2k = collections.defaultdict(collections.Counter)
    for i, d in D.items():
        gh, ko = d.get('monsters', []), [m['n'] for m in S[str(i)]['mons']]
        if len(gh) != len(ko):
            sys.exit('시나리오 %d: GHS 몬스터 %d개 vs 페이지 %d개 — 순서 가정이 깨졌습니다.'
                     % (i, len(gh), len(ko)))
        for a, b in zip(gh, ko):
            m2k[a][b] += 1
    bad = {k: dict(v) for k, v in m2k.items() if len(v) > 1}
    if bad:
        sys.exit('한글 이름이 엇갈리는 몬스터가 있습니다: %s' % json.dumps(bad, ensure_ascii=False))
    return {k: v.most_common(1)[0][0] for k, v in m2k.items()}


def counts(entry):
    """[[n2,e2],[n3,e3],[n4,e4]] — 인원수별 일반/정예 1 또는 0."""
    out = []
    for p in ('player2', 'player3', 'player4'):
        t = entry.get(p, entry.get('type'))
        out.append([1 if t == 'normal' else 0, 1 if t in ('elite', 'boss') else 0])
    return out


def build_map(D, names):
    order = sorted(names)               # MON 배열 순서 = slug 정렬 순서
    idx = {s: i for i, s in enumerate(order)}
    MAP = {}
    for i, d in D.items():
        rooms = []
        for r in d.get('rooms', []):
            room = {'n': r['roomNumber']}
            if 'ref' in r:        room['t'] = r['ref']
            if r.get('initial'):  room['s'] = 1
            if r.get('rooms'):    room['to'] = r['rooms']
            if r.get('treasures'):room['tr'] = r['treasures']
            if r.get('objectives'): room['ob'] = r['objectives']
            if 'marker' in r:     room['mk'] = str(r['marker'])
            # 같은 몬스터의 여러 스탠디를 한 줄로 합친다
            agg = collections.OrderedDict()
            for e in r.get('monster', []):
                slug = e['name']
                cur = agg.setdefault(slug, {'m': idx[slug], 'c': [[0, 0], [0, 0], [0, 0]],
                                            'b': 1 if e.get('type') == 'boss' else 0})
                if e.get('type') == 'boss':
                    cur['b'] = 1
                for k, (n, el) in enumerate(counts(e)):
                    cur['c'][k][0] += n
                    cur['c'][k][1] += el
            mons = []
            for slug, v in agg.items():
                m = {'m': v['m'], 'c': v['c']}
                if v['b']:
                    m['b'] = 1
                mons.append(m)
            if mons:
                room['m'] = mons
            rooms.append(room)
        ent = {}
        if rooms:
            ent['r'] = rooms
        objs = []
        for o in d.get('objectives', []):
            ob = {'n': o.get('name', '')}
            if o.get('escort'):  ob['e'] = 1
            if o.get('health'):  ob['h'] = str(o['health'])
            if o.get('marker'):  ob['mk'] = str(o['marker'])
            objs.append(ob)
        if objs:
            ent['o'] = objs
        if ent:
            MAP[str(i)] = ent
    return order, MAP


def main():
    html = load_html()
    S, _ = parse_const(html, 'S')
    D = load_ghs()
    names = build_monster_names(D, S)
    order, MAP = build_map(D, names)
    MON = [names[s] for s in order]
    # slug 의 ":+N" 접미사는 레벨 보정이라 이름 뒤에 표기한다
    MON = [n + (' (레벨 %s)' % s.split(':')[1] if ':' in s else '')
           for n, s in zip(MON, order)]

    blob = ('const MON=%s;\nconst MAP=%s;\n'
            % (json.dumps(MON, ensure_ascii=False, separators=(',', ':')),
               json.dumps(MAP, ensure_ascii=False, separators=(',', ':'))))
    marker = '// ---------- battle setup data (generated by tools/build_battle_data.py) ----------\n'
    start = html.find(marker)
    if start == -1:
        sys.exit('index.html 에 생성 블록 표시가 없습니다. 먼저 표시 주석을 넣으세요.')
    end = html.find('// ---------- /battle setup data ----------', start)
    html = html[:start + len(marker)] + blob + html[end:]
    open(HTML, 'w', encoding='utf-8', newline='').write(html)
    print('MON %d개, MAP %d개 시나리오, blob %.1fKB' % (len(MON), len(MAP), len(blob) / 1024))


if __name__ == '__main__':
    main()
