# -*- coding: utf-8 -*-
"""index.html 의 const LMON / MIMG / OVN / OIMG / TIMG / LAY 블록(시나리오별 배치도)을 만든다.

바탕이 되는 배치는 Gloomhaven Line of Sight Tool(gloomhaven.one)이 들고 있는 **공식 시나리오 배치**다.
타일 이름·격자 위치·회전이 그대로 들어 있어 타일끼리 정확히 맞물린다(95개 전 시나리오에서 헥스 겹침 0).
그 위에 datahaven(Tabletop Simulator) 의 몬스터·장애물·보물 좌표를 얹는다.

입력
  tools/tile_shapes.json      타일 60종의 헥스 모양·이미지·오프셋 + 시나리오 95개 공식 배치
  assets/tiles/*.webp         타일 이미지 (Creator Pack, CC BY-NC-SA 4.0)
  tools/dh_cache/<번호>.json   datahaven 배치 좌표 (몬스터·장애물·문)
  tools/ghs_cache/<번호>.json  GHS 데이터 (방 번호·보스 판정·수량 교차 검증)

좌표
  타일 격자는 LOS 앱과 같은 odd-q 오프셋 좌표(홀수 열이 반 칸 아래).
  화면 픽셀은 헥스 외접반지름 45px 기준: 열 간격 67.5, 행 간격 √3·45, 홀수 열은 행의 절반만큼 내려간다.
  이미지 배치도 앱과 같다: 타일 요소 원점 + (-38, -16), 회전별 보정이 있으면 그 값(원본 60px 기준 × 0.75).

datahaven 좌표는 방향이 다를 수 있어 시나리오마다 (거울, 60도 회전, 평행이동)을 맞춰 얹는다.

사용법
  python tools/extract_tile_shapes.py   # 타일 모양·공식 배치 추출
  python tools/fetch_tile_images.py     # 타일 이미지 내려받기
  python tools/fetch_layouts.py         # datahaven 원본
  python tools/fetch_token_images.py    # 몬스터·오버레이 그림 (MIMG/OIMG 의 입력)
  python tools/build_map_layout.py      # index.html 갱신  (--check 는 검증만)
"""
import json, glob, os, collections, math, io, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _emit as E

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DH = os.path.join(ROOT, 'tools', 'dh_cache')
GHS = os.path.join(ROOT, 'tools', 'ghs_cache')
SHAPES = os.path.join(ROOT, 'tools', 'tile_shapes.json')
HTML = os.path.join(ROOT, 'index.html')

S45 = 45.0
COLW = 1.5 * S45                 # 67.5
ROWH = math.sqrt(3) * S45        # 77.94
IMG_DX, IMG_DY = -38.0, -16.0    # .img-wrap 기본 오프셋

LONG, SHORT = 1.3125, 0.7577718  # datahaven(TTS) 헥스 간격
K = 1.5 / LONG
SQ3 = math.sqrt(3)

# 방 단위 재정렬 기준: 전체 정렬에서 방 요소가 하나라도 바닥 밖이면 후보가 되고,
# 방 단위로 맞췄을 때 전부 들어가거나(완전) 3개 이상 늘면서 90% 이상 들어갈 때만 바꾼다.
# (1개쯤 벗어난 방은 문 헥스 위 요소 같은 정상 예외일 수 있어 건드리지 않는다)
ROOM_GAIN, ROOM_MIN = 3, 0.9
DEBUG_ROOMS = '--rooms' in sys.argv

MARK = '// ---------- hex layout data (generated by tools/build_map_layout.py) ----------\n'
ENDMARK = '// ---------- /hex layout data ----------'
TILE_RE = re.compile(r'[A-N][1-4][ab]')


# ---------------------------------------------------------------- 헥스 좌표

def to_cube(x, y):
    """odd-q 오프셋 -> 큐브"""
    return (x, y - (x - (x & 1)) // 2)


def to_off(q, rr):
    return (q, rr + (q - (q & 1)) // 2)


def rot_cube(q, rr, k):
    s = -q - rr
    for _ in range(k % 6):
        q, rr, s = -rr, -s, -q
    return q, rr


def refl_cube(q, rr):
    return (q, -q - rr)


def hex_px(x, y):
    """헥스의 좌상단 픽셀 (LOS 앱 jt())"""
    return COLW * x, ROWH * y + (ROWH / 2 if x & 1 else 0)


def hex_center(x, y):
    px, py = hex_px(x, y)
    return px + S45, py + ROWH / 2


# ---------------------------------------------------------------- 타일 배치

def rotate_shape(hexes, rot):
    """LOS 앱의 회전(P)과 같은 결과: 중심 기준 60도 회전 후 (0,0)으로 정규화"""
    k = (rot // 60) % 6
    if not k:
        return list(hexes)
    cx = round(sum(h[0] for h in hexes) / len(hexes))
    cy = round(sum(h[1] for h in hexes) / len(hexes))
    cq, cr = to_cube(cx, cy)
    out = []
    for x, y in hexes:
        q, rr = to_cube(x, y)
        nq, nr = rot_cube(q - cq, rr - cr, k)
        out.append(to_off(nq + cq, nr + cr))
    mx = min(o[0] for o in out)
    my = min(o[1] for o in out)
    res = []
    for x, y in out:
        x -= mx
        y -= my
        if (mx & 1) and (x & 1):
            y -= 1
        res.append((x, y))
    if min(r[1] for r in res) < 0:
        res = [(x, y + 1) for x, y in res]
    return res


def place(tiles, name, X, Y, rot):
    """전역 오프셋 좌표의 헥스 목록과 타일 요소 크기를 돌려준다."""
    local = rotate_shape([(c - 1, r - 1) for c, r in tiles[name]['hexes']], rot)
    glob = [(hx + X, hy + Y + (1 if (X & 1) and (hx & 1) else 0)) for hx, hy in local]
    w = max(hex_px(x, y)[0] for x, y in local) + 2 * S45
    h = max(hex_px(x, y)[1] for x, y in local) + ROWH
    return glob, local, w, h


def image_offset(tile, rot):
    """회전별 이미지 오프셋(px, s=45 기준)"""
    offs = tile.get('offsets') or {}
    dx, dy = IMG_DX, IMG_DY
    src = offs.get(str(rot))
    if src is None and tile.get('sym180') and rot >= 180:
        src = offs.get(str(rot - 180))
    if src:
        if 'left' in src:
            dx = 0.75 * src['left']
        if 'top' in src:
            dy = 0.75 * src['top']
    return dx, dy


# ---------------------------------------------------------------- datahaven

def _xyz(v):
    """datahaven 좌표·회전은 {x,y,z} 또는 [x,y,z] 두 형식이 섞여 있다(133개가 목록 형식)."""
    if isinstance(v, dict):
        return v
    if isinstance(v, list) and len(v) == 3:
        return {'x': v[0], 'y': v[1], 'z': v[2]}
    return None


def room_items(room):
    """(종류, 이름, 위치, 추가정보) 목록. 종류: start, monster, overlay, marker(시나리오 표식 글자), figure(호위 대상·아군)"""
    out = []
    st = room.get('startTiles')
    for g in ([st] if isinstance(st, dict) else (st or [])):
        if isinstance(g, dict):
            for t in g.get('tiles', []):
                p = _xyz(t.get('position'))
                if p:
                    out.append(('start', g.get('name'), p, None))
    for m in room.get('monsters', []):
        for t in m.get('tiles', []):
            p = _xyz(t.get('position'))
            if p:
                out.append(('monster', m.get('name'), p, t.get('numCharacters') or {}))
    for ov in room.get('overlayTiles', []):
        for ty in ov.get('type', []):
            for t in ty.get('tiles', []):
                p = _xyz(t.get('position'))
                if not p:
                    continue
                if ty.get('name') == 'Scenario Aid Token':          # 시나리오북의 a·b·1… 표식
                    out.append(('marker', str(t.get('name', '')), p, None))
                    continue
                out.append(('overlay', ty.get('name'), p, _xyz(t.get('rotation'))))
                for tok in t.get('tokens') or []:                    # 압력판·제단 등에 붙은 표식 글자
                    out.append(('marker', str(tok), p, None))
    for fg in room.get('figures') or []:
        p = _xyz(fg.get('position'))
        if p:
            out.append(('figure', fg.get('name'), p, None))
    return out


def origin_of(d):
    for room in d.get('rooms', []):
        for kind, name, p, _ in room_items(room):
            if kind == 'monster':
                return p['x'], p['z']
    for room in d.get('rooms', []):
        for kind, name, p, _ in room_items(room):
            return p['x'], p['z']
    return 0.0, 0.0


def dh_mapper(d):
    """datahaven position -> 자체 배가 좌표(임의 방향). 나중에 공식 격자에 맞춘다."""
    gt = d.get('gridType', 1)
    ox, oz = origin_of(d)

    def snap(p):
        X = (p['x'] - ox) * K
        Y = (p['z'] - oz) * K
        if gt != 1:
            X, Y = Y, -X
        c = X / 1.5
        r = Y / (SQ3 / 2)
        ci, ri = round(c), round(r)
        if (ci + ri) % 2:
            ri += 1 if r - ri > 0 else -1
        return ci, ri, max(abs(c - ci), abs(r - ri) / 2)
    return snap


# TTS(datahaven) 좌표와 공식 격자는 항상 거울 관계다. 판정이 갈리는 시나리오 61개가 전부 거울=1 이었고,
# 거울=0 이 뽑히던 곳은 모두 동점(대칭 배치)이라 잘못 고른 것이었다(#33 이 위아래로 뒤집혔던 원인).
MIRROR = 1


def dh_float(d):
    """datahaven 위치 -> 반올림하지 않은 큐브 좌표 (타일 중심처럼 헥스 중심이 아닌 점용)"""
    gt = d.get('gridType', 1)
    ox, oz = origin_of(d)

    def f(p):
        X = (p['x'] - ox) * K
        Y = (p['z'] - oz) * K
        if gt != 1:
            X, Y = Y, -X
        c = X / 1.5
        r = Y / (SQ3 / 2)
        return c, (r - c) / 2
    return f


def room_anchor(room, fmap, own_cube, k):
    """TTS 타일 중심을 공식 타일 중심에 겹치게 하는 이동량(실수). 회전 k 마다 다르다."""
    pos = [t['position'] for t in (room.get('mapTiles') or []) if isinstance(t, dict) and isinstance(t.get('position'), dict)]
    # 타일이 여러 장인 방은 모양이 같은 타일(A3/A4 등)의 이름이 두 데이터에서 엇갈릴 수 있어 중심 평균을 믿지 않는다 (#33)
    if len(pos) != 1 or not own_cube:
        return None
    pts = [fmap(p) for p in pos]
    q = sum(a for a, b in pts) / len(pts)
    rr = sum(b for a, b in pts) / len(pts)
    if MIRROR:
        q, rr = refl_cube(q, rr)
    q, rr = rot_cube(q, rr, k)
    oq = sum(a for a, b in own_cube) / len(own_cube)
    orr = sum(b for a, b in own_cube) / len(own_cube)
    return oq - q, orr - rr


# 공식 배치(gloomhaven.one)의 타일 위치가 틀린 경우의 수정: {시나리오: {타일: (x, y, 회전)}} — 현재 없음
PIECE_FIX = {}

# 자동 정렬이 시나리오북과 어긋나 시나리오북 페이지와 직접 대조해 정한 변환 (거울, 회전, 이동)
# #36: TTS 데이터가 다른 시나리오와 반대 거울로 만들어져 있다(악마=L 타일, 경비병·벽·보물=I1b/B2b 가 이 값에서만 맞음)
TF_OVERRIDE = {36: (0, 0, 4, 8)}

# 시나리오북과 대조해 남은 차이를 배치도에 안내한다 (LAY[id].w)
MAP_WARN = {
    35: '공식 배치 데이터의 타일 배치가 시나리오북과 좌우로 달라, 일부 몬스터·장애물 위치가 시나리오북과 다를 수 있습니다.',
    36: '공식 배치 데이터의 타일 배치가 시나리오북과 좌우로 달라, 일부 몬스터·장애물 위치가 시나리오북과 다를 수 있습니다.',
}
EMPTY_WARN = '이 시나리오는 몬스터·장애물 위치 데이터가 없어 타일만 보여 줍니다. 배치는 시나리오북을 확인하세요.'

# 여러 헥스짜리 오버레이. datahaven 좌표는 그중 한 헥스(기준 헥스)만 가리키므로
# TTS 회전값으로 나머지 헥스를 만든다. 방향 규칙(MULTI_PHI, MULTI_SIGN)은 전 시나리오에서
# 추가 헥스가 바닥 위에·다른 요소와 겹치지 않게 떨어지는 비율로 정했다(24가지 중 270°/-1: 193개 중 바닥 안 188, 겹침 10).
MULTI = {'Bookcase': 2, 'Table': 2, 'Sarcophagus A': 2, 'Boulder 2': 2, 'Log': 2, 'Dark Pit': 2,
         'Shelf': 2, 'Wall Section': 2, 'Boulder 3': 3, 'Tree': 3}
MULTI_PHI = float(os.environ.get('MULTI_PHI', 270))
MULTI_SIGN = int(os.environ.get('MULTI_SIGN', -1))
MULTI_TRI = int(os.environ.get('MULTI_TRI', 1))      # 3칸짜리 삼각형이 어느 쪽으로 펼쳐지는지 (+1/-1)
HEX_WORLD = SQ3 * LONG / 1.5                         # TTS 좌표에서 이웃 헥스 중심 간 거리


def multi_parts(name, p, rot):
    """여러 헥스 오버레이의 추가 헥스 위치들(TTS 좌표)"""
    n = MULTI.get(name)
    if not n or not isinstance(rot, dict):
        return []
    th = math.radians(rot.get('y', 0) + MULTI_PHI)
    out = []
    for j in range(1, n):
        a = th + (math.radians(60) * MULTI_TRI if j == 2 else 0)
        out.append({'x': p['x'] + HEX_WORLD * math.cos(a), 'z': p['z'] + MULTI_SIGN * HEX_WORLD * math.sin(a)})
    return out


SPAWN_Y = 1.7
# 호위 대상·아군 등 datahaven figures 의 한국어 이름 (S 데이터 줄거리 표기와 맞춤)
FIGURE_KO = {'Hail': '헤일', 'Villager': '마을 주민', 'Orchid': '오키드', 'Captive Orchid': '붙잡힌 오키드',
             'Redthorn': '레드쏜', 'Fish': '물고기', 'Vocal Chord': '성대'}

# datahaven 에 좌표가 없어 시나리오북 페이지를 보고 직접 옮긴 배치 (LAY 좌표계, 원점 정규화 후).
# #34: 시나리오북 45쪽. 드레이크의 인원수별 구성(2/3/4인: 0 없음 1 일반 2 정예 3 보스)은 모형 띠 색에서 읽었고
#      4인 합계가 GHS 와 일치한다(분비액 일반2·정예1, 발톱 정예2). 3칸 바위 a·b·c 는 첫 칸 외 추가 칸 표시.
MANUAL = {
    34: {
        'm': [('spitting-drake', 7, 3, 1, 2, 2), ('spitting-drake', 7, 7, 1, 1, 1), ('spitting-drake', 4, 1, 0, 0, 1),
              ('rending-drake', 5, 2, 2, 2, 2), ('rending-drake', 5, 8, 0, 0, 2), ('elder-drake', 6, 5, 3, 3, 3)],
        'v': [('Boulder 3', [(7, 4), (7, 5), (6, 5)]), ('Boulder 3', [(3, 0), (3, 1), (2, 1)]),
              ('Boulder 3', [(3, 8), (3, 9), (2, 9)]),
              ('Nest', [(6, 2)]), ('Nest', [(5, 7)]), ('Nest', [(3, 6)]), ('Nest', [(2, 3)]),
              ('Coin 1', [(7, 0)]), ('Coin 1', [(7, 1)]), ('Coin 1', [(7, 2)]), ('Coin 1', [(6, 1)]),
              ('Coin 1', [(7, 8)]), ('Coin 1', [(6, 9)]), ('Treasure Chest Horizontal', [(7, 9)])],
        's': [(2, 4), (2, 5), (2, 6), (1, 3), (1, 4), (1, 5), (1, 6)],
        'k': [('a', 3, 8), ('b', 3, 1), ('c', 6, 5)],
        'n': '이 시나리오는 원본 좌표 데이터가 없어 시나리오북 페이지를 보고 직접 옮겨 넣었습니다.',
    },
}

TILE_FIT_MAX = 1.5   # 타일 중심 맞춤의 평균 오차(헥스)가 이 이하일 때만 믿는다


def tile_fit(d, pieces, fmap):
    """TTS 타일 위치를 공식 타일 중심에 겹치게 하는 회전 k 와 이동량(실수)을 찾는다.
    요소만으로는 대칭 배치에서 180도 돌린 답과 구분이 안 되는 경우(#35 등)를 잡는다.
    반환: (k, (dq, dr), 평균 오차) 또는 None"""
    cen = {}
    for pc in pieces:
        cs = [to_cube(*hx) for hx in pc['hx']]
        cen[pc['t']] = (sum(a for a, b in cs) / len(cs), sum(b for a, b in cs) / len(cs))
    pairs = []
    for room in d.get('rooms', []):
        for t in (room.get('mapTiles') or []):
            if not (isinstance(t, dict) and t.get('tile') and isinstance(t.get('position'), dict)):
                continue
            m = [n for n in cen if n.startswith(t['tile'])]
            if len(m) == 1:
                pairs.append((fmap(t['position']), cen[m[0]]))
    if len(pairs) < 2:          # 타일 한 장으로는 회전을 정할 수 없다
        return None
    best = None
    for k in range(6):
        T = []
        for (q, rr), o in pairs:
            if MIRROR:
                q, rr = refl_cube(q, rr)
            T.append((rot_cube(q, rr, k), o))
        dq = sum(o[0] - a[0] for a, o in T) / len(T)
        dr = sum(o[1] - a[1] for a, o in T) / len(T)
        err = 0.0
        for a, o in T:
            x, y = a[0] + dq - o[0], a[1] + dr - o[1]
            err += (abs(x) + abs(y) + abs(x + y)) / 2
        err /= len(T)
        if best is None or err < best[2]:
            best = (k, (dq, dr), err)
    return best if best[2] <= TILE_FIT_MAX else None


def align(elem_cube, floor_cube, elem_tiles=None, floor_tile=None, fit=None):
    """datahaven 큐브 좌표를 공식 바닥에 겹치게 하는 (거울, 회전, 이동) 을 찾는다.
    1순위: 바닥 위에 떨어지는 요소 수. 2순위: 요소가 자기 방의 타일(이름이 같은 타일) 위에 떨어지는 수.
    대칭에 가까운 배치에서 180도 돌린 답과 구분하려고 2순위를 쓴다."""
    if not elem_cube or not floor_cube:
        return (MIRROR, 0, 0, 0), 0
    fc = (sum(q for q, r in floor_cube) / len(floor_cube),
          sum(r for q, r in floor_cube) / len(floor_cube))
    best = None
    for k in ([fit[0]] if fit else range(6)):
        V = []
        for q, rr in elem_cube:
            if MIRROR:
                q, rr = refl_cube(q, rr)
            V.append(rot_cube(q, rr, k))
        if fit:
            # 타일 중심 맞춤이 정한 회전을 쓰고, 이동은 그 추정값 둘레 ±2 에서 바닥 적중으로 다듬는다
            d0, span = (round(fit[1][0]), round(fit[1][1])), 2
        else:
            vc = (sum(q for q, r in V) / len(V), sum(r for q, r in V) / len(V))
            # 무게중심 차이 주변을 넉넉히 훑는다(±2 로는 #13 의 정답을 놓쳤다)
            d0, span = (round(fc[0] - vc[0]), round(fc[1] - vc[1])), 6
        for dq in range(d0[0] - span, d0[0] + span + 1):
            for dr in range(d0[1] - span, d0[1] + span + 1):
                hit = own = 0
                for j, (q, rr) in enumerate(V):
                    cq = (q + dq, rr + dr)
                    if cq in floor_cube:
                        hit += 1
                        if elem_tiles and floor_tile and any(floor_tile[cq].startswith(n) for n in elem_tiles[j]):
                            own += 1
                near = -(abs(dq - fit[1][0]) + abs(dr - fit[1][1])) if fit else 0
                score = (hit, own, near, k == 0)
                if best is None or score > best[1]:
                    best = ((MIRROR, k, dq, dr), score)
    return best[0], best[1][0]


def align_room(elem_cube, floor_cube, base, anchor_of=None):
    """한 방의 요소를 그 방의 타일 바닥에 맞춘다. 거울은 고정, 회전·이동만 찾는다.
    바닥에 들어가는 개수가 같으면 TTS 타일 중심이 공식 타일 중심에 가장 가까운 쪽(anchor_of(k)),
    그 정보가 없으면 전체 정렬(base)에 가까운 쪽을 고른다. 요소가 적은 방은 들어가는 자리가 여러 곳이라 필요하다."""
    mir, k0, dq0, dr0 = base
    fc = (sum(q for q, r in floor_cube) / len(floor_cube),
          sum(r for q, r in floor_cube) / len(floor_cube))
    best = None
    for k in range(6):
        V = []
        for q, rr in elem_cube:
            if mir:
                q, rr = refl_cube(q, rr)
            V.append(rot_cube(q, rr, k))
        anc = anchor_of(k) if anchor_of else None
        vc = (sum(q for q, r in V) / len(V), sum(r for q, r in V) / len(V))
        d0 = (round(fc[0] - vc[0]), round(fc[1] - vc[1]))
        for dq in range(d0[0] - 4, d0[0] + 5):
            for dr in range(d0[1] - 4, d0[1] + 5):
                hit = sum(1 for q, rr in V if (q + dq, rr + dr) in floor_cube)
                if anc:
                    a, b = dq - anc[0], dr - anc[1]
                    cost = (abs(a) + abs(b) + abs(a + b)) / 2      # 큐브 거리
                else:
                    cost = (k != k0) * 100 + abs(dq - dq0) + abs(dr - dr0)
                if best is None or hit > best[1] or (hit == best[1] and cost < best[2]):
                    best = ((mir, k, dq, dr), hit, cost)
    return best[0], best[1]


def room_tiles(room):
    """datahaven 방의 타일 이름(면 표기 없음, 예: 'C2')"""
    mt = room.get('mapTiles') or []
    return [t.get('tile') for t in mt if isinstance(t, dict) and t.get('tile')]


def apply_tf(tf, c, r):
    """자체 배가 좌표 -> 공식 오프셋 좌표"""
    mir, k, dq, dr = tf
    q, rr = c, (r - c) // 2
    if mir:
        q, rr = refl_cube(q, rr)
    q, rr = rot_cube(q, rr, k)
    return to_off(q + dq, rr + dr)


# ---------------------------------------------------------------- 분류표

OVL = {
    'Coin 1': ('coin', '돈'),
    'Treasure Chest Horizontal': ('treasure', '보물 상자'),
    'Treasure Chest Vertical': ('treasure', '보물 상자'),
    'Water 1': ('difficult', '물'),
    'Rubble': ('difficult', '잔해'),
    'Stalagmites': ('difficult', '석순'),
    'Thorns': ('hazard', '가시덤불'),
    'Poison Gas': ('hazard', '독가스'),
    'Hot Coals 1': ('hazard', '뜨거운 숯'),
    'Spike Trap': ('trap', '가시 함정'),
    'Bear Trap': ('trap', '곰덫'),
    'Pressure Plate': ('special', '압력판'),
    'Stairs Horizontal': ('special', '계단'),
    'Stairs Vertical': ('special', '계단'),
    'Dark Pit': ('special', '어둠의 구덩이'),
    'Altar Horizontal': ('special', '제단'),
    'Altar Vertical': ('special', '제단'),
    'Crystal': ('special', '수정'),
    'Fountain': ('special', '분수'),
    'Boulder': ('obstacle', '바위'),
    'Boulder 2': ('obstacle', '바위'),
    'Boulder 3': ('obstacle', '바위'),
    'Stone Pillar': ('obstacle', '돌기둥'),
    'Rock Column': ('obstacle', '암석 기둥'),
    'Wall Section': ('obstacle', '벽'),
    'Bush': ('obstacle', '덤불'),
    'Log': ('obstacle', '통나무'),
    'Tree': ('obstacle', '나무'),
    'Stump': ('obstacle', '그루터기'),
    'Barrel': ('obstacle', '통'),
    'Bookcase': ('obstacle', '책장'),
    'Cabinet': ('obstacle', '수납장'),
    'Crate B': ('obstacle', '상자'),
    'Shelf': ('obstacle', '선반'),
    'Table': ('obstacle', '탁자'),
    'Totem': ('obstacle', '토템'),
    'Sarcophagus A': ('obstacle', '석관'),
    'Nest': ('obstacle', '둥지'),
}
# 오버레이 종류(한국어 이름) -> Virtual Gloomhaven Board 의 오버레이 그림 (Creator Pack, CC BY-NC-SA 4.0).
# 여러 헥스짜리 장애물은 첫 조각 그림을 쓴다. 통로는 재질이 여러 가지라 한 종류로 묶여 있어 그림을 쓰지 않는다.
OVIMG = {
    '돈': 'treasure-coin', '보물 상자': 'treasure-chest',
    '물': 'difficult-terrain-water', '잔해': 'difficult-terrain-rubble', '석순': 'obstacle-stalagmites',
    '가시덤불': 'hazard-thorns', '독가스': 'trap-poison', '뜨거운 숯': 'hazard-hot-coals',
    '가시 함정': 'trap-spike', '곰덫': 'trap-bear', '압력판': 'corridor-pressure-plate-1',
    '계단': 'difficult-terrain-stairs', '어둠의 구덩이': 'obstacle-dark-pit', '제단': 'obstacle-altar',
    '수정': 'obstacle-crystal', '분수': 'obstacle-fountain', '바위': 'obstacle-boulder-1',
    '돌기둥': 'obstacle-pillar', '암석 기둥': 'obstacle-rock-column', '벽': 'obstacle-wall-section',
    '덤불': 'obstacle-bush', '통나무': 'difficult-terrain-log', '나무': 'obstacle-tree-3',
    '그루터기': 'obstacle-stump', '통': 'obstacle-barrel', '책장': 'obstacle-bookcase',
    '수납장': 'obstacle-cabinet', '상자': 'obstacle-crate', '선반': 'obstacle-shelf',
    '탁자': 'obstacle-table', '토템': 'obstacle-totem', '석관': 'obstacle-sarcophagus',
    '둥지': 'obstacle-nest',
}
# 여러 헥스 장애물의 조각 그림 (VGB). 꼭짓점이 위인 헥스 기준으로 2칸은 [왼쪽, 오른쪽],
# 3칸은 [왼쪽 위, 오른쪽 위, 아래] 순서로 맞물린다. 칸 수별로 고른다(바위는 1·2·3칸 그림이 다르다).
OVPARTS = {
    '석관': {2: ['obstacle-sarcophagus', 'obstacle-sarcophagus-2']},
    '탁자': {2: ['obstacle-table', 'obstacle-table-2']},
    '책장': {2: ['obstacle-bookcase', 'obstacle-bookcase-2']},
    '선반': {2: ['obstacle-shelf', 'obstacle-shelf-2']},
    '통나무': {2: ['difficult-terrain-log', 'difficult-terrain-log-2']},
    '벽': {2: ['obstacle-wall-section', 'obstacle-wall-section-2']},
    '어둠의 구덩이': {2: ['obstacle-dark-pit', 'obstacle-dark-pit-2']},
    '바위': {2: ['obstacle-boulder-2', 'obstacle-boulder-2-2'], 3: ['obstacle-boulder-3', 'obstacle-boulder-3-2', 'obstacle-boulder-3-3']},
    '나무': {3: ['obstacle-tree-3', 'obstacle-tree-3-2', 'obstacle-tree-3-3']},
}
MONDIR = os.path.join(ROOT, 'assets', 'monsters')
OVDIR = os.path.join(ROOT, 'assets', 'overlays')

DOOR = {
    'Stone Door Horizontal': ('door', '돌문'),
    'Stone Door Vertical': ('door', '돌문'),
    'Wooden Door Horizontal': ('door', '나무문'),
    'Wooden Door Vertical': ('door', '나무문'),
    'Light Fog': ('fog', '옅은 안개'),
    'Dark Fog': ('fog', '짙은 안개'),
}


def classify(name):
    if name in OVL:
        return OVL[name]
    if name in DOOR:
        return DOOR[name]
    if 'Corridor' in str(name):
        return ('corridor', '통로')
    return ('other', str(name))


def norm(n):
    return re.sub(r'[^a-z0-9]+', '-', str(n).lower()).strip('-')


def korean_names(html):
    """GHS slug -> 한글 이름. index.html 의 S[id].mons 가 GHS monsters 와 같은 순서라는 성질로 역산한다.
    같은 모형을 보스 이름으로 부르는 시나리오가 있어(#67 '신비한 골렘' = stone-golem) 가장 많이 쓰인 이름을 고른다."""
    S = json.loads(re.search(r'const S=(\{.*?\});\n', html, re.S).group(1))
    cnt = collections.defaultdict(collections.Counter)
    for f in glob.glob(os.path.join(GHS, '*.json')):
        g = json.load(open(f, encoding='utf-8'))
        s = S.get(str(int(g['index'])))
        if not s:
            continue
        for slug, m in zip(g.get('monsters', []), s['mons']):
            cnt[slug.split(':')[0]][re.sub(r'\s*\(레벨.*\)$', '', m['n'])] += 1
    return {slug: c.most_common(1)[0][0] for slug, c in cnt.items()}


def boss_names(gd):
    return {e['name'].split(':')[0] for r in gd.get('rooms', []) for e in r.get('monster', [])
            if e.get('type') == 'boss'}


# ---------------------------------------------------------------- 생성

def monster_slugs():
    """datahaven 몬스터 이름(정규화). LMON 의 순서이자 GHS 썸네일 파일명(gh-<slug>.png)."""
    D = [json.load(open(f, encoding='utf-8')) for f in glob.glob(os.path.join(DH, '*.json'))]
    return sorted({norm(n) for d in D for room in d.get('rooms', [])
                   for k, n, p, e in room_items(room) if k == 'monster'})


def build():
    data = json.load(open(SHAPES, encoding='utf-8'))
    tiles, layouts = data['tiles'], data['layouts']
    D = {int(os.path.basename(f)[:-5]): json.load(open(f, encoding='utf-8'))
         for f in glob.glob(os.path.join(DH, '*.json'))}
    G = {}
    for f in glob.glob(os.path.join(GHS, '*.json')):
        g = json.load(open(f, encoding='utf-8'))
        G[int(g['index'])] = g
    html = open(HTML, encoding='utf-8').read()
    kor = korean_names(html)

    names = monster_slugs()
    nidx = {n: i for i, n in enumerate(names)}
    LMON = [kor.get(n, n) for n in names]

    ovkinds = {}

    def ov_index(name):
        cat, ko = classify(name)
        key = (cat, ko)
        if key not in ovkinds:
            ovkinds[key] = len(ovkinds)
        return ovkinds[key]

    timg = {}
    LAY = {}
    stat = collections.Counter()

    for i in range(1, 96):
        lay = layouts.get(str(i)) or layouts.get(i)
        d = D.get(i)
        if not lay:
            continue

        # ---- 공식 배치: 타일 이미지와 바닥 헥스
        pieces, floor = [], {}
        for p in lay['pieces']:
            nm = p['name']
            if not TILE_RE.fullmatch(nm):
                continue
            if nm in PIECE_FIX.get(i, {}):
                fx, fy, fr = PIECE_FIX[i][nm]
                p = dict(p, x=fx, y=fy, rot=fr)
            glob_hexes, local, w, h = place(tiles, nm, p['x'], p['y'], p['rot'])
            bx, by = hex_px(p['x'], p['y'])
            dx, dy = image_offset(tiles[nm], p['rot'])
            t = tiles[nm]
            if nm not in timg:
                timg[nm] = [t['image'], t['size'][0], t['size'][1]]
            pieces.append({'t': nm, 'x': round(bx + dx, 1), 'y': round(by + dy, 1),
                           'r': p['rot'], 'hx': glob_hexes})
            for hx in glob_hexes:
                floor[hx] = nm

        if not floor:
            continue

        floor_cube = {to_cube(*hx) for hx in floor}

        # ---- datahaven 요소를 공식 격자에 맞추기
        mons, ovs, starts, marks, figs = [], [], [], [], []
        rooms_of_tile = {}
        if d:
            snap = dh_mapper(d)
            gd = G.get(i, {})
            boss = boss_names(gd)
            elems, parts = [], []
            for ri, room in enumerate(d.get('rooms', []), 1):
                for kind, name, p, extra in room_items(room):
                    # TTS 에서 판 아래 높이(y≈1.65)에 둔 몬스터 21개는 처음부터 놓이지 않는 것들이다
                    # (#19 #48 #57 #69 #74 #83 #92 — 시나리오북 특수 규칙의 '나중에 등장/배치하지 않음').
                    # 좌표도 헥스 중심에서 반 칸 어긋나 있어(오차≈0.5) 자리를 정할 수 없으므로 초기 배치도에서 뺀다.
                    # 보스는 큰 받침대라 y≈1.82, 일반 몬스터는 y≈2.07 이다.
                    if kind == 'monster' and p.get('y', 2) < SPAWN_Y:
                        stat['나중 등장'] += 1
                        continue
                    c, r, res = snap(p)
                    if res > 0.3:
                        stat['격자 이탈'] += 1
                        continue
                    elems.append((ri, kind, name, extra, c, r))
                    if kind == 'overlay':
                        for q in multi_parts(name, p, extra):
                            c2, r2, res2 = snap(q)
                            if res2 <= 0.3 and (c2, r2) != (c, r):
                                parts.append((ri, name, c, r, c2, r2))   # 기준 헥스 (c,r) 에 딸린 추가 칸
                            else:
                                stat['부분 격자 이탈'] += 1
            dh_rooms = d.get('rooms', [])
            sel_el = [(ri, c, r) for ri, kind, name, extra, c, r in elems
                      if kind in ('monster', 'overlay') and 'Corridor' not in str(name)]
            solid = [(c, (r - c) // 2) for ri, c, r in sel_el]
            floor_tile = {to_cube(*hx): t for hx, t in floor.items()}
            fit = tile_fit(d, pieces, dh_float(d))
            if fit:
                stat['타일 맞춤'] += 1
            tf, hit = align(solid, floor_cube, [room_tiles(dh_rooms[ri - 1]) for ri, c, r in sel_el], floor_tile, fit)
            if i in TF_OVERRIDE:
                tf = TF_OVERRIDE[i]

            # 방마다 자기 타일에 다 들어가는지 확인하고, 어긋난 방만 따로 다시 맞춘다
            # (TTS 쪽 방 배치가 공식 배치와 다른 시나리오가 있다. 예: #33)
            room_tf = {}
            for ri in (sorted({e[0] for e in elems}) if i not in TF_OVERRIDE else []):
                tnames = room_tiles(dh_rooms[ri - 1])
                own = {to_cube(*hx) for hx, t in floor.items() if any(t.startswith(n) for n in tnames)}
                # 통로 오버레이는 방 사이에 걸치므로 뺀다 (시작 헥스 그룹 이름에도 'Corridor' 가 들어갈 수 있어 kind 로 거른다)
                # 기준: 몬스터·장애물·시작 헥스(#3 #49 #70 은 시작 헥스로 맞춰야 판 안에 들어온다)
                mine = [(c, r) for rj, kind, name, extra, c, r in elems
                        if rj == ri and kind in ('monster', 'overlay', 'start')
                        and not (kind == 'overlay' and 'Corridor' in str(name))]
                marks_r = [(c, r) for rj, kind, name, extra, c, r in elems if rj == ri and kind == 'marker']
                if not own or not mine:
                    continue
                # 전체 정렬로 바닥(어느 타일이든) 위에 잘 올라가 있으면 건드리지 않는다.
                # 모양이 같은 타일(A1~A4 등)은 두 데이터의 이름 표기가 달라 '자기 타일' 기준으로 옮기면 오히려 틀린다.
                cur = sum(1 for c, r in mine if apply_tf(tf, c, r) in floor)
                if cur == len(mine):
                    continue
                fmap = dh_float(d)
                ntf, nhit = align_room([(c, (r - c) // 2) for c, r in mine], own, tf,
                                       lambda k, room=dh_rooms[ri - 1]: room_anchor(room, fmap, own, k))
                nfull = sum(1 for c, r in mine if apply_tf(ntf, c, r) in floor)
                if DEBUG_ROOMS:
                    print('  #%d 방%d %s: 바닥 안 %d/%d -> 방 단위 %d/%d (자기 타일 %d)' % (
                        i, ri, tnames, cur, len(mine), nfull, len(mine), nhit))
                # 같은 방의 표식이 바닥 밖으로 밀려나면 받지 않는다. #33 복도 방은 시작 헥스 2칸이 원래 타일 사이
                # 통로 칸에 있어 '전부 바닥 안'으로 옮기면 출구 표식 a 6개가 모두 타일 밖으로 나갔다.
                mk_before = sum(1 for c, r in marks_r if apply_tf(tf, c, r) in floor)
                mk_after = sum(1 for c, r in marks_r if apply_tf(ntf, c, r) in floor)
                if mk_after < mk_before:
                    continue
                if nfull > cur and (nfull == len(mine) or (nfull - cur >= ROOM_GAIN and nfull >= len(mine) * ROOM_MIN)):
                    room_tf[ri] = ntf
                    stat['방 재정렬'] += 1

            for ri, kind, name, extra, c, r in elems:
                if kind not in ('monster', 'overlay') or 'Corridor' in str(name):
                    continue
                stat['요소'] += 1
                if apply_tf(room_tf.get(ri, tf), c, r) in floor:
                    stat['바닥 안'] += 1

            centers = collections.defaultdict(list)
            for ri, kind, name, extra, c, r in elems:
                hx = apply_tf(room_tf.get(ri, tf), c, r)
                if kind == 'monster':
                    tt = []
                    for pl in ('2', '3', '4'):
                        v = (extra or {}).get(pl)
                        tt.append(3 if (v and norm(name) in boss) else
                                  (2 if v == 2 else (1 if v == 1 else 0)))
                    if any(tt):
                        mons.append([nidx[norm(name)], hx[0], hx[1]] + tt)
                elif kind == 'start':
                    starts.append([hx[0], hx[1]])
                elif kind == 'marker':
                    marks.append([name, hx[0], hx[1]])
                    continue
                elif kind == 'figure':
                    figs.append([FIGURE_KO.get(name, name), hx[0], hx[1]])
                else:
                    ovs.append([ov_index(name), hx[0], hx[1]])
                if hx in floor:
                    centers[floor[hx]].append(ri)
            # 여러 헥스 오버레이의 나머지 헥스 (정렬에는 쓰지 않고, 같은 방 변환으로 옮기기만 한다)
            taken = {(m[1], m[2]) for m in mons} | {(v[1], v[2]) for v in ovs}
            # 추가 칸은 기준 헥스의 오버레이 항목에 [[x,y],...] 로 붙인다 → 한 장애물 = 한 항목(그림을 이어 붙이고 범례도 1개로 센다)
            own = {}
            for v in ovs:
                own.setdefault((v[0], v[1], v[2]), v)
            for ri, name, c0, r0, c, r in parts:
                t = room_tf.get(ri, tf)
                base, hx = apply_tf(t, c0, r0), apply_tf(t, c, r)
                stat['부분'] += 1
                if hx in floor:
                    stat['부분 바닥 안'] += 1
                if hx in taken:
                    stat['부분 겹침'] += 1
                    if DEBUG_ROOMS:
                        print('  겹침 #%d %s %s' % (i, name, hx))
                v = own.get((ov_index(name), base[0], base[1]))
                if v is None:
                    continue
                if len(v) == 3:
                    v.append([])
                v[3].append([hx[0], hx[1]])
                taken.add(hx)
            # 타일별 방 번호: 그 타일 위에 있던 요소들의 최빈 방
            for tname, lst in centers.items():
                rooms_of_tile[tname] = collections.Counter(lst).most_common(1)[0][0]

        # ---- 문·통로 (공식 배치)
        doors = []
        for p in lay['pieces']:
            if p['name'] in ('door', 'corridor'):
                doors.append([1 if p['name'] == 'corridor' else 0, p['x'], p['y'], p['rot'],
                              p.get('color') or 0])

        if DEBUG_ROOMS and os.environ.get('DUMP') == str(i):
            print('DUMP marks', marks); print('DUMP starts', starts)
            print('DUMP pieces', [(pc['t'], sorted(pc['hx'])[:3]) for pc in pieces])
        # ---- 원점 정규화
        allx = [hx[0] for pc in pieces for hx in pc['hx']] + [e[1] for e in mons] + \
               [e[1] for e in ovs] + [e[0] for e in starts] + [dd[1] for dd in doors]
        ally = [hx[1] for pc in pieces for hx in pc['hx']] + [e[2] for e in mons] + \
               [e[2] for e in ovs] + [e[1] for e in starts] + [dd[2] for dd in doors]
        mx, my = min(allx), min(ally)
        if mx & 1:
            mx -= 1                      # 홀수 열 패리티 보존
        px0, py0 = hex_px(mx, my)

        out_pieces = []
        for pc in pieces:
            out_pieces.append([pc['t'], round(pc['x'] - px0, 1), round(pc['y'] - py0, 1), pc['r'],
                               rooms_of_tile.get(pc['t'], 0)])
        rooms_hex = collections.defaultdict(list)
        for pc in pieces:
            for hx in pc['hx']:
                rooms_hex[rooms_of_tile.get(pc['t'], 0)].append((hx[0] - mx, hx[1] - my))

        ent = {'p': out_pieces,
               'f': {str(k): E.rle_off(v) for k, v in rooms_hex.items()},
               'w': round(max(hx[0] for pc in pieces for hx in pc['hx']) - mx),
               'h': round(max(hx[1] for pc in pieces for hx in pc['hx']) - my)}
        # 요소가 거의 없으면(#34: datahaven 에 엘더 드레이크 하나뿐) 엉뚱한 자리에 찍느니 그리지 않는다
        if len(mons) + len(ovs) + len(starts) < 3:
            mons, ovs, starts, marks, figs = [], [], [], [], []
            ent['n'] = EMPTY_WARN
        elif i in MAP_WARN:
            ent['n'] = MAP_WARN[i]
        if mons:
            ent['m'] = [[m[0], m[1] - mx, m[2] - my, m[3], m[4], m[5]] for m in mons]
        if ovs:
            ent['v'] = [[v[0], v[1] - mx, v[2] - my] + ([[[a - mx, b - my] for a, b in v[3]]] if len(v) > 3 else []) for v in ovs]
        if starts:
            ent['s'] = [[s[0] - mx, s[1] - my] for s in starts]
        if marks:
            ent['k'] = [[k[0], k[1] - mx, k[2] - my] for k in marks]
        if figs:
            ent['g'] = [[g[0], g[1] - mx, g[2] - my] for g in figs]
        if doors:
            ent['d'] = [[dd[0], dd[1] - mx, dd[2] - my, dd[3], dd[4]] for dd in doors]
        if i in MANUAL:
            man = MANUAL[i]
            ent['m'] = [[nidx[s], x, y, a, b, c] for s, x, y, a, b, c in man['m']]
            ent['v'] = [[ov_index(n), hexes[0][0], hexes[0][1]] + ([[list(q) for q in hexes[1:]]] if len(hexes) > 1 else [])
                        for n, hexes in man['v']]
            ent['s'] = [list(s) for s in man['s']]
            ent['k'] = [list(k) for k in man['k']]
            ent['n'] = man['n']
        LAY[str(i)] = ent

    OVN = [[k[0], k[1]] for k in sorted(ovkinds, key=ovkinds.get)]
    # 그림 파일이 실제로 있는 것만 넣는다 (없으면 빈 문자열 -> 색 도형으로 그림)
    MIMG = [n if os.path.exists(os.path.join(MONDIR, n + '.webp')) else '' for n in names]
    OIMG = [OVIMG.get(o[1], '') for o in OVN]
    OIMG = [f if f and os.path.exists(os.path.join(OVDIR, f + '.webp')) else '' for f in OIMG]
    OPARTS = {}
    for j, o in enumerate(OVN):
        sets = {str(n): fs for n, fs in OVPARTS.get(o[1], {}).items()
                if all(os.path.exists(os.path.join(OVDIR, f + '.webp')) for f in fs)}
        if sets:
            OPARTS[str(j)] = sets
    stat['조각'] = OPARTS
    return LMON, OVN, timg, LAY, stat, MIMG, OIMG


def main():
    LMON, OVN, TIMG, LAY, stat, MIMG, OIMG = build()
    print('시나리오 %d개 · 타일 이미지 %d종 · 몬스터 %d종 · 오버레이 %d종'
          % (len(LAY), len(TIMG), len(LMON), len(OVN)))
    print('처음부터 놓이지 않는 몬스터(판 아래 높이) 제외 %d' % stat['나중 등장'])
    print('여러 헥스 추가 %d개: 바닥 안 %d, 다른 요소와 겹침 %d, 격자 이탈 %d' % (
        stat['부분'], stat['부분 바닥 안'], stat['부분 겹침'], stat['부분 격자 이탈']))
    print('몬스터 그림 %d/%d · 오버레이 그림 %d/%d' % (sum(map(bool, MIMG)), len(MIMG),
                                                sum(map(bool, OIMG)), len(OIMG)))
    print('datahaven 요소 %d개 중 공식 바닥 안 %d개 (%.1f%%), 격자 이탈 %d, 타일 맞춤 %d, 방 단위 재정렬 %d'
          % (stat['요소'], stat['바닥 안'], 100 * stat['바닥 안'] / max(1, stat['요소']),
             stat['격자 이탈'], stat['타일 맞춤'], stat['방 재정렬']))
    if '--check' in sys.argv:
        return
    blob = ('const LMON=%s;\nconst MIMG=%s;\nconst OVN=%s;\nconst OIMG=%s;\nconst OPARTS=%s;\nconst TIMG=%s;\nconst LAY=%s;\n' % (
        json.dumps(LMON, ensure_ascii=False, separators=(',', ':')),
        json.dumps(MIMG, ensure_ascii=False, separators=(',', ':')),
        json.dumps(OVN, ensure_ascii=False, separators=(',', ':')),
        json.dumps(OIMG, ensure_ascii=False, separators=(',', ':')),
        json.dumps(stat['조각'], ensure_ascii=False, separators=(',', ':')),
        json.dumps(TIMG, ensure_ascii=False, separators=(',', ':')),
        json.dumps(LAY, ensure_ascii=False, separators=(',', ':'))))
    html = open(HTML, encoding='utf-8').read()
    st = html.find(MARK)
    if st == -1:
        sys.exit('index.html 에 생성 블록 표시가 없습니다.')
    en = html.find(ENDMARK, st)
    open(HTML, 'w', encoding='utf-8', newline='').write(html[:st + len(MARK)] + blob + html[en:])
    print('blob %.1fKB' % (len(blob) / 1024))


if __name__ == '__main__':
    main()
