# -*- coding: utf-8 -*-
"""index.html 의 const LMON / OVN / TIMG / LAY 블록(시나리오별 배치도)을 만든다.

바탕이 되는 배치는 Gloomhaven Line of Sight Tool(gloomhaven.one)이 들고 있는 **공식 시나리오 배치**다.
타일 이름·격자 위치·회전이 그대로 들어 있어 타일끼리 정확히 맞물린다(95개 전 시나리오에서 헥스 겹침 0).
그 위에 datahaven(Tabletop Simulator) 의 몬스터·장애물·보물 좌표를 얹는다.

입력
  tools/tile_shapes.json      타일 60종의 헥스 모양·이미지·오프셋 + 시나리오 95개 공식 배치
  assets/tiles/*.webp         타일 이미지 (Creator Pack, CC BY-NC-SA 4.0)
  tools/dh_cache/<번호>.json   datahaven 배치 좌표 (몬스터·장애물·문)
  tools/ghs_cache/<번호>.json  GHS 데이터 (방 번호·보스 판정·수량 교차 검증)

좌표
  타일 격자는 LOS 앱과 같은 odd-q 오프셋 좌표(홀수 열이 반 칸 아래).
  화면 픽셀은 헥스 외접반지름 45px 기준: 열 간격 67.5, 행 간격 √3·45, 홀수 열은 행의 절반만큼 내려간다.
  이미지 배치도 앱과 같다: 타일 요소 원점 + (-38, -16), 회전별 보정이 있으면 그 값(원본 60px 기준 × 0.75).

datahaven 좌표는 방향이 다를 수 있어 시나리오마다 (거울, 60도 회전, 평행이동)을 맞춰 얹는다.

사용법
  python tools/extract_tile_shapes.py   # 타일 모양·공식 배치 추출
  python tools/fetch_tile_images.py     # 타일 이미지 내려받기
  python tools/fetch_layouts.py         # datahaven 원본
  python tools/build_map_layout.py      # index.html 갱신  (--check 는 검증만)
"""
import json, glob, os, collections, math, io, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _emit as E

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DH = os.path.join(ROOT, 'tools', 'dh_cache')
GHS = os.path.join(ROOT, 'tools', 'ghs_cache')
SHAPES = os.path.join(ROOT, 'tools', 'tile_shapes.json')
HTML = os.path.join(ROOT, 'index.html')

S45 = 45.0
COLW = 1.5 * S45                 # 67.5
ROWH = math.sqrt(3) * S45        # 77.94
IMG_DX, IMG_DY = -38.0, -16.0    # .img-wrap 기본 오프셋

LONG, SHORT = 1.3125, 0.7577718  # datahaven(TTS) 헥스 간격
K = 1.5 / LONG
SQ3 = math.sqrt(3)

MARK = '// ---------- hex layout data (generated by tools/build_map_layout.py) ----------\n'
ENDMARK = '// ---------- /hex layout data ----------'
TILE_RE = re.compile(r'[A-N][1-4][ab]')


# ---------------------------------------------------------------- 헥스 좌표

def to_cube(x, y):
    """odd-q 오프셋 -> 큐브"""
    return (x, y - (x - (x & 1)) // 2)


def to_off(q, rr):
    return (q, rr + (q - (q & 1)) // 2)


def rot_cube(q, rr, k):
    s = -q - rr
    for _ in range(k % 6):
        q, rr, s = -rr, -s, -q
    return q, rr


def refl_cube(q, rr):
    return (q, -q - rr)


def hex_px(x, y):
    """헥스의 좌상단 픽셀 (LOS 앱 jt())"""
    return COLW * x, ROWH * y + (ROWH / 2 if x & 1 else 0)


def hex_center(x, y):
    px, py = hex_px(x, y)
    return px + S45, py + ROWH / 2


# ---------------------------------------------------------------- 타일 배치

def rotate_shape(hexes, rot):
    """LOS 앱의 회전(P)과 같은 결과: 중심 기준 60도 회전 후 (0,0)으로 정규화"""
    k = (rot // 60) % 6
    if not k:
        return list(hexes)
    cx = round(sum(h[0] for h in hexes) / len(hexes))
    cy = round(sum(h[1] for h in hexes) / len(hexes))
    cq, cr = to_cube(cx, cy)
    out = []
    for x, y in hexes:
        q, rr = to_cube(x, y)
        nq, nr = rot_cube(q - cq, rr - cr, k)
        out.append(to_off(nq + cq, nr + cr))
    mx = min(o[0] for o in out)
    my = min(o[1] for o in out)
    res = []
    for x, y in out:
        x -= mx
        y -= my
        if (mx & 1) and (x & 1):
            y -= 1
        res.append((x, y))
    if min(r[1] for r in res) < 0:
        res = [(x, y + 1) for x, y in res]
    return res


def place(tiles, name, X, Y, rot):
    """전역 오프셋 좌표의 헥스 목록과 타일 요소 크기를 돌려준다."""
    local = rotate_shape([(c - 1, r - 1) for c, r in tiles[name]['hexes']], rot)
    glob = [(hx + X, hy + Y + (1 if (X & 1) and (hx & 1) else 0)) for hx, hy in local]
    w = max(hex_px(x, y)[0] for x, y in local) + 2 * S45
    h = max(hex_px(x, y)[1] for x, y in local) + ROWH
    return glob, local, w, h


def image_offset(tile, rot):
    """회전별 이미지 오프셋(px, s=45 기준)"""
    offs = tile.get('offsets') or {}
    dx, dy = IMG_DX, IMG_DY
    src = offs.get(str(rot))
    if src is None and tile.get('sym180') and rot >= 180:
        src = offs.get(str(rot - 180))
    if src:
        if 'left' in src:
            dx = 0.75 * src['left']
        if 'top' in src:
            dy = 0.75 * src['top']
    return dx, dy


# ---------------------------------------------------------------- datahaven

def room_items(room):
    out = []
    st = room.get('startTiles')
    for g in ([st] if isinstance(st, dict) else (st or [])):
        if isinstance(g, dict):
            for t in g.get('tiles', []):
                if isinstance(t.get('position'), dict):
                    out.append(('start', g.get('name'), t['position'], None))
    for m in room.get('monsters', []):
        for t in m.get('tiles', []):
            if isinstance(t.get('position'), dict):
                out.append(('monster', m.get('name'), t['position'], t.get('numCharacters') or {}))
    for ov in room.get('overlayTiles', []):
        for ty in ov.get('type', []):
            for t in ty.get('tiles', []):
                if isinstance(t.get('position'), dict):
                    out.append(('overlay', ty.get('name'), t['position'], t.get('rotation')))
    return out


def origin_of(d):
    for room in d.get('rooms', []):
        for kind, name, p, _ in room_items(room):
            if kind == 'monster':
                return p['x'], p['z']
    for room in d.get('rooms', []):
        for kind, name, p, _ in room_items(room):
            return p['x'], p['z']
    return 0.0, 0.0


def dh_mapper(d):
    """datahaven position -> 자체 배가 좌표(임의 방향). 나중에 공식 격자에 맞춘다."""
    gt = d.get('gridType', 1)
    ox, oz = origin_of(d)

    def snap(p):
        X = (p['x'] - ox) * K
        Y = (p['z'] - oz) * K
        if gt != 1:
            X, Y = Y, -X
        c = X / 1.5
        r = Y / (SQ3 / 2)
        ci, ri = round(c), round(r)
        if (ci + ri) % 2:
            ri += 1 if r - ri > 0 else -1
        return ci, ri, max(abs(c - ci), abs(r - ri) / 2)
    return snap


def align(elem_cube, floor_cube):
    """datahaven 큐브 좌표를 공식 바닥에 겹치게 하는 (거울, 회전, 이동) 을 찾는다."""
    if not elem_cube or not floor_cube:
        return (0, 0, 0, 0), 0
    fc = (sum(q for q, r in floor_cube) / len(floor_cube),
          sum(r for q, r in floor_cube) / len(floor_cube))
    best = None
    for mir in (0, 1):
        for k in range(6):
            V = []
            for q, rr in elem_cube:
                if mir:
                    q, rr = refl_cube(q, rr)
                V.append(rot_cube(q, rr, k))
            vc = (sum(q for q, r in V) / len(V), sum(r for q, r in V) / len(V))
            d0 = (round(fc[0] - vc[0]), round(fc[1] - vc[1]))
            for dq in range(d0[0] - 2, d0[0] + 3):
                for dr in range(d0[1] - 2, d0[1] + 3):
                    hit = sum(1 for q, rr in V if (q + dq, rr + dr) in floor_cube)
                    if best is None or hit > best[1]:
                        best = ((mir, k, dq, dr), hit)
    return best


def apply_tf(tf, c, r):
    """자체 배가 좌표 -> 공식 오프셋 좌표"""
    mir, k, dq, dr = tf
    q, rr = c, (r - c) // 2
    if mir:
        q, rr = refl_cube(q, rr)
    q, rr = rot_cube(q, rr, k)
    return to_off(q + dq, rr + dr)


# ---------------------------------------------------------------- 분류표

OVL = {
    'Coin 1': ('coin', '돈'),
    'Treasure Chest Horizontal': ('treasure', '보물 상자'),
    'Treasure Chest Vertical': ('treasure', '보물 상자'),
    'Water 1': ('difficult', '물'),
    'Rubble': ('difficult', '잔해'),
    'Stalagmites': ('difficult', '석순'),
    'Thorns': ('hazard', '가시덤불'),
    'Poison Gas': ('hazard', '독가스'),
    'Hot Coals 1': ('hazard', '뜨거운 숯'),
    'Spike Trap': ('trap', '가시 함정'),
    'Bear Trap': ('trap', '곰덫'),
    'Pressure Plate': ('special', '압력판'),
    'Stairs Horizontal': ('special', '계단'),
    'Stairs Vertical': ('special', '계단'),
    'Dark Pit': ('special', '어둠의 구덩이'),
    'Altar Horizontal': ('special', '제단'),
    'Altar Vertical': ('special', '제단'),
    'Crystal': ('special', '수정'),
    'Fountain': ('special', '분수'),
    'Boulder': ('obstacle', '바위'),
    'Boulder 2': ('obstacle', '바위'),
    'Boulder 3': ('obstacle', '바위'),
    'Stone Pillar': ('obstacle', '돌기둥'),
    'Rock Column': ('obstacle', '암석 기둥'),
    'Wall Section': ('obstacle', '벽'),
    'Bush': ('obstacle', '덤불'),
    'Log': ('obstacle', '통나무'),
    'Tree': ('obstacle', '나무'),
    'Stump': ('obstacle', '그루터기'),
    'Barrel': ('obstacle', '통'),
    'Bookcase': ('obstacle', '책장'),
    'Cabinet': ('obstacle', '수납장'),
    'Crate B': ('obstacle', '상자'),
    'Shelf': ('obstacle', '선반'),
    'Table': ('obstacle', '탁자'),
    'Totem': ('obstacle', '토템'),
    'Sarcophagus A': ('obstacle', '석관'),
    'Nest': ('obstacle', '둥지'),
}
DOOR = {
    'Stone Door Horizontal': ('door', '돌문'),
    'Stone Door Vertical': ('door', '돌문'),
    'Wooden Door Horizontal': ('door', '나무문'),
    'Wooden Door Vertical': ('door', '나무문'),
    'Light Fog': ('fog', '옅은 안개'),
    'Dark Fog': ('fog', '짙은 안개'),
}


def classify(name):
    if name in OVL:
        return OVL[name]
    if name in DOOR:
        return DOOR[name]
    if 'Corridor' in str(name):
        return ('corridor', '통로')
    return ('other', str(name))


def norm(n):
    return re.sub(r'[^a-z0-9]+', '-', str(n).lower()).strip('-')


def korean_names(html):
    mon = json.loads(re.search(r'const MON=(\[.*?\]);\n', html, re.S).group(1))
    slugs = sorted({s for f in glob.glob(os.path.join(GHS, '*.json'))
                    for s in json.load(open(f, encoding='utf-8')).get('monsters', [])})
    return {slug.split(':')[0]: re.sub(r'\s*\(레벨.*\)$', '', name)
            for name, slug in zip(mon, slugs)}


def boss_names(gd):
    return {e['name'].split(':')[0] for r in gd.get('rooms', []) for e in r.get('monster', [])
            if e.get('type') == 'boss'}


# ---------------------------------------------------------------- 생성

def build():
    data = json.load(open(SHAPES, encoding='utf-8'))
    tiles, layouts = data['tiles'], data['layouts']
    D = {int(os.path.basename(f)[:-5]): json.load(open(f, encoding='utf-8'))
         for f in glob.glob(os.path.join(DH, '*.json'))}
    G = {}
    for f in glob.glob(os.path.join(GHS, '*.json')):
        g = json.load(open(f, encoding='utf-8'))
        G[int(g['index'])] = g
    html = open(HTML, encoding='utf-8').read()
    kor = korean_names(html)

    names = sorted({norm(n) for d in D.values() for room in d.get('rooms', [])
                    for k, n, p, e in room_items(room) if k == 'monster'})
    nidx = {n: i for i, n in enumerate(names)}
    LMON = [kor.get(n, n) for n in names]

    ovkinds = {}

    def ov_index(name):
        cat, ko = classify(name)
        key = (cat, ko)
        if key not in ovkinds:
            ovkinds[key] = len(ovkinds)
        return ovkinds[key]

    timg = {}
    LAY = {}
    stat = collections.Counter()

    for i in range(1, 96):
        lay = layouts.get(str(i)) or layouts.get(i)
        d = D.get(i)
        if not lay:
            continue

        # ---- 공식 배치: 타일 이미지와 바닥 헥스
        pieces, floor = [], {}
        for p in lay['pieces']:
            nm = p['name']
            if not TILE_RE.fullmatch(nm):
                continue
            glob_hexes, local, w, h = place(tiles, nm, p['x'], p['y'], p['rot'])
            bx, by = hex_px(p['x'], p['y'])
            dx, dy = image_offset(tiles[nm], p['rot'])
            t = tiles[nm]
            if nm not in timg:
                timg[nm] = [t['image'], t['size'][0], t['size'][1]]
            pieces.append({'t': nm, 'x': round(bx + dx, 1), 'y': round(by + dy, 1),
                           'r': p['rot'], 'hx': glob_hexes})
            for hx in glob_hexes:
                floor[hx] = nm

        if not floor:
            continue

        floor_cube = {to_cube(*hx) for hx in floor}

        # ---- datahaven 요소를 공식 격자에 맞추기
        mons, ovs, starts = [], [], []
        rooms_of_tile = {}
        if d:
            snap = dh_mapper(d)
            gd = G.get(i, {})
            boss = boss_names(gd)
            elems = []
            for ri, room in enumerate(d.get('rooms', []), 1):
                for kind, name, p, extra in room_items(room):
                    c, r, res = snap(p)
                    if res > 0.3:
                        stat['격자 이탈'] += 1
                        continue
                    elems.append((ri, kind, name, extra, c, r))
            solid = [(c, (r - c) // 2) for ri, kind, name, extra, c, r in elems
                     if kind != 'start' and 'Corridor' not in str(name)]
            tf, hit = align(solid, floor_cube)
            stat['요소'] += len(solid)
            stat['바닥 안'] += hit

            centers = collections.defaultdict(list)
            for ri, kind, name, extra, c, r in elems:
                hx = apply_tf(tf, c, r)
                if kind == 'monster':
                    tt = []
                    for pl in ('2', '3', '4'):
                        v = (extra or {}).get(pl)
                        tt.append(3 if (v and norm(name) in boss) else
                                  (2 if v == 2 else (1 if v == 1 else 0)))
                    if any(tt):
                        mons.append([nidx[norm(name)], hx[0], hx[1]] + tt)
                elif kind == 'start':
                    starts.append([hx[0], hx[1]])
                else:
                    ovs.append([ov_index(name), hx[0], hx[1]])
                if hx in floor:
                    centers[floor[hx]].append(ri)
            # 타일별 방 번호: 그 타일 위에 있던 요소들의 최빈 방
            for tname, lst in centers.items():
                rooms_of_tile[tname] = collections.Counter(lst).most_common(1)[0][0]

        # ---- 문·통로 (공식 배치)
        doors = []
        for p in lay['pieces']:
            if p['name'] in ('door', 'corridor'):
                doors.append([1 if p['name'] == 'corridor' else 0, p['x'], p['y'], p['rot'],
                              p.get('color') or 0])

        # ---- 원점 정규화
        allx = [hx[0] for pc in pieces for hx in pc['hx']] + [e[1] for e in mons] + \
               [e[1] for e in ovs] + [e[0] for e in starts] + [dd[1] for dd in doors]
        ally = [hx[1] for pc in pieces for hx in pc['hx']] + [e[2] for e in mons] + \
               [e[2] for e in ovs] + [e[1] for e in starts] + [dd[2] for dd in doors]
        mx, my = min(allx), min(ally)
        if mx & 1:
            mx -= 1                      # 홀수 열 패리티 보존
        px0, py0 = hex_px(mx, my)

        out_pieces = []
        for pc in pieces:
            out_pieces.append([pc['t'], round(pc['x'] - px0, 1), round(pc['y'] - py0, 1), pc['r'],
                               rooms_of_tile.get(pc['t'], 0)])
        rooms_hex = collections.defaultdict(list)
        for pc in pieces:
            for hx in pc['hx']:
                rooms_hex[rooms_of_tile.get(pc['t'], 0)].append((hx[0] - mx, hx[1] - my))

        ent = {'p': out_pieces,
               'f': {str(k): E.rle_off(v) for k, v in rooms_hex.items()},
               'w': round(max(hx[0] for pc in pieces for hx in pc['hx']) - mx),
               'h': round(max(hx[1] for pc in pieces for hx in pc['hx']) - my)}
        if mons:
            ent['m'] = [[m[0], m[1] - mx, m[2] - my, m[3], m[4], m[5]] for m in mons]
        if ovs:
            ent['v'] = [[v[0], v[1] - mx, v[2] - my] for v in ovs]
        if starts:
            ent['s'] = [[s[0] - mx, s[1] - my] for s in starts]
        if doors:
            ent['d'] = [[dd[0], dd[1] - mx, dd[2] - my, dd[3], dd[4]] for dd in doors]
        LAY[str(i)] = ent

    OVN = [[k[0], k[1]] for k in sorted(ovkinds, key=ovkinds.get)]
    return LMON, OVN, timg, LAY, stat


def main():
    LMON, OVN, TIMG, LAY, stat = build()
    print('시나리오 %d개 · 타일 이미지 %d종 · 몬스터 %d종 · 오버레이 %d종'
          % (len(LAY), len(TIMG), len(LMON), len(OVN)))
    print('datahaven 요소 %d개 중 공식 바닥 안 %d개 (%.1f%%), 격자 이탈 %d'
          % (stat['요소'], stat['바닥 안'], 100 * stat['바닥 안'] / max(1, stat['요소']),
             stat['격자 이탈']))
    if '--check' in sys.argv:
        return
    blob = ('const LMON=%s;\nconst OVN=%s;\nconst TIMG=%s;\nconst LAY=%s;\n' % (
        json.dumps(LMON, ensure_ascii=False, separators=(',', ':')),
        json.dumps(OVN, ensure_ascii=False, separators=(',', ':')),
        json.dumps(TIMG, ensure_ascii=False, separators=(',', ':')),
        json.dumps(LAY, ensure_ascii=False, separators=(',', ':'))))
    html = open(HTML, encoding='utf-8').read()
    st = html.find(MARK)
    if st == -1:
        sys.exit('index.html 에 생성 블록 표시가 없습니다.')
    en = html.find(ENDMARK, st)
    open(HTML, 'w', encoding='utf-8', newline='').write(html[:st + len(MARK)] + blob + html[en:])
    print('blob %.1fKB' % (len(blob) / 1024))


if __name__ == '__main__':
    main()
